config/routes.rb
Rails.application.routes.draw do
  root to: 'businesses#index'
  get 'ui(/:action)', controller: 'ui'
  get '/register', to: 'users#new', as: 'register'
  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/businesses/search', to: 'businesses#search', as: 'search_businesses'

  resources :businesses, only: [:show, :new, :create] do
    resources :reviews, only: [:create]
  end
  resources :users, only: [:create, :show]
  resources :sessions, only: [:create]
  resources :reviews, only: [:index]

end

app/models/business.rb
class Business < ActiveRecord::Base
  default_scope { order('created_at DESC') }
  has_many :reviews

  validates :name, presence: true, uniqueness: true, length: { minimum: 3 }

  def latest_review
    reviews.first
  end

  def self.search_by_name(query)
    where("name ILIKE ?", "%#{query}%").order 'created_at DESC'
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  default_scope { order('created_at DESC') }
  belongs_to :user
  belongs_to :business

  validates :body, presence: true, length: {minimum: 10}
  validates_uniqueness_of :user_id, scope: :business_id

  def business_name
    business.name
  end

  def username
    user.username
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews, -> { order('created_at DESC') }
  has_secure_password validations: false

  validates :username, presence: true
  validates :email, presence: true, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: { minimum: 6 }, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user

  def logged_in?
    !!session[:user_id]
  end

  def require_logout
    if logged_in?
      flash[:error] = "You're already logged in!"
      redirect_to root_path
    end
  end

  def require_login
    unless logged_in?
      flash[:error] = "You must log in to do that."
      redirect_to login_path
    end
  end

  def current_user
    @current_user ||= User.find session[:user_id] if logged_in?
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def index
    @businesses = Business.limit 10
  end

  def show
    @business = Business.find params[:id]
    @review = Review.new
  end

  def new
    @business = Business.new
  end

  def create
    @business = Business.new business_params
    if @business.save
      flash[:notice] = 'You added a new business!'
      redirect_to root_path
    else
      flash.now[:error] = 'Your submission contained validation errors. Please try again.'
      render :new
    end
  end

  def search
    @search_results = Business.search_by_name params[:query]
  end

  private

  def business_params
    params.require(:business).permit :name
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_login, only: [:create]

  def create
    @business = Business.find params[:business_id]
    @review = @business.reviews.new review_params.merge!(user: current_user)
    if @review.save
      flash[:notice] = "Your review was posted!"
      redirect_to business_path(@business)
    else
      flash.now[:error] = "Oh no! There's something wrong with your review."
      render 'businesses/show'
    end
  end

  def index
    @reviews = Review.limit 10
  end

  private

    def review_params
      params.require(:review).permit(:body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_logout, except: [:destroy]

  def create
    user = User.find_by email: params[:email]
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "You've successfully logged in as #{user.username}."
      redirect_to root_path
    else
      flash.now[:error] = 'Your login information was incorrect. Please verify your submission and try agian.'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Successfully logged out.'
    redirect_to root_path
  end
end

app/controllers/ui_controller.rb
class UiController < ApplicationController
  layout 'application'  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show]
  before_action :require_logout, only: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:notice] = "You're now registered for Yelpr! Sorry, we don't send confirmation emails yet <|-.-|>"
      redirect_to root_path
    else
      flash.now[:error] = "Your submissions was invalid. Please fix the highlighted fields."
      render :new
    end
  end

  def show
    @user = User.find params[:id]
  end

private

  def user_params
    params.require(:user).permit :username, :email, :password
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def date_string(timestamp:)
    timestamp.strftime("%e %b %Y")
  end

end

app/views/businesses/_business.html.haml
%a.list-group-item(href="#{business_path(business)}")
  %h5.list-group-item-heading #{business.name}
  - if business.reviews.any?
    %p.list-group-item-text <em>#{business.latest_review.body}</em> – by #{business.latest_review.username} on #{date_string(timestamp: business.latest_review.created_at)}

app/views/businesses/index.html.haml
.panel.panel-primary
  .panel-heading
    %h4.panel-title Businesses
  .panel-body
    %p Check out some of the latest businesses registered to Yelpr!
  .list-group#payload
    = render @businesses

app/views/businesses/new.html.haml
.panel.panel-primary
  .panel-heading
    %h4.panel-title Register your business on yelpr!
  .panel-body
    = bootstrap_form_for @business, layout: :horizontal, label_col: 'col-sm-2', control_col: 'col-sm-6' do |f|
      %fieldset
        = f.text_field :name, label: 'Business Name'
      %fieldset
        .col-sm-offset-2.col-sm-10
          %button.btn.btn-primary(type="submit") Sign Up

app/views/businesses/search.html.haml
.panel.panel-primary
  / Default panel contents
  .panel-heading
    %h4.panel-title Search Results
  .panel-body
    %p We found #{pluralize(@search_results.count, 'business')} related to your search:
  / List group
  .list-group
    = render @search_results

app/views/businesses/show.html.haml
.panel.panel-primary
  / Business name
  .panel-heading
    %h4.panel-title Latest Reviews of #{@business.name}
  .panel-body
    / Business reviews
    .list-group
      = render @business.reviews
    / New review form
    - if logged_in?
      = form_for [@business, @review] do |f|
        .form-group.row
          %fieldset
          .col-sm-6
            = f.label :body, "Share your experience with #{@business.name}"
            = f.text_area(:body, placeholder: "Type your review here.", rows: 4, class: 'form-control')
        .form-group
          %fieldset.actions
          .col-sm-2
            %button.btn.btn-primary(type="submit") Submit

app/views/layouts/application.html.haml
!!! 5
%html(lang="en-US")
  %head
    %title YelpClone
    %meta(charset="UTF-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = csrf_meta_tag
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
  %body
    %header
    = render 'shared/header'
    %section.content.clearfix
      .container-fluid
        = render 'shared/messages'
        = yield
    %footer
      .container-fluids
        &nbsp &copy 2016 Yelpr

app/views/reviews/_review.html.haml
/ user path coming soon!
%a.list-group-item(href="#{user_path(review.user)}")
  %h5.list-group-item-heading #{review.username}
  %p.list-group-item-text <em>#{review.body}</em> – about #{review.business_name} on #{date_string(timestamp: review.created_at)}

app/views/reviews/index.html.haml
.panel.panel-primary
  / Default panel contents
  .panel-heading
    %h4.panel-title Recent Reviews:
  .panel-body
    / List group
    .list-group#payload
      =render @reviews

app/views/shared/_header.html.haml
%section.header
  %nav.navbar.navbar-default
    .container-fluid
      -# Brand and toggle get grouped for better mobile display
      .navbar-header
        %button.navbar-toggle.collapsed(type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false")
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#{root_path}") Yelpr

      -# Collect the nav links, forms, and other content for toggling
      .collapse.navbar-collapse#bs-example-navbar-collapse-1
        %ul.nav.navbar-nav
          %li
            =link_to "Recent Reviews", reviews_path
            <span class="sr-only"> (current)</span>
          %li
            =link_to "Add New Business", new_business_path

        = form_tag search_businesses_path, method: "get", class: "navbar-form navbar-left" do
          .form-group
            = text_field_tag :query, "", placeholder: "Search businesses", class: "form-control"
          %button.btn.btn-default#submit_search(type="submit")
            %i.glyphicon.glyphicon-search
        -unless logged_in?
          %ul.nav.navbar-nav.navbar-right
            %li
              =link_to "Register", register_path
            %li
              =link_to "Log In", login_path
        -else
          %ul.nav.navbar-nav.navbar-right
            %li
              =link_to "My Profile", user_path(current_user)
            %li
              =link_to "Log Out", logout_path
-#
  %form.navbar-form.navbar-left(role="search", method='get', url="#{search_businesses_path}")
    .form-group
      %input.form-control(type="text" placeholder="Find a Business", name="query")
    %button.btn.btn-default(type="submit")
      %i.glyphicon.glyphicon-search

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-dismissible alert-#{name == 'notice' ? 'success' : 'danger'}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/ui/add_business.html.haml
.panel.panel-primary
  .panel-heading
    %h4.panel-title Register your business on yelpr!
  .panel-body
    %form.form-horizontal
      .form-group
        %label.col-sm-2.control-label(for="inputEmail3") Business Name
        .col-sm-10
          %input#inputEmail3.form-control(placeholder="Name" :type="string")
      .form-group
        .col-sm-offset-2.col-sm-10
          %button.btn.btn-primary(type="submit") Sign Up

app/views/ui/business_profile.html.haml
.panel.panel-primary
  / Default panel contents
  .panel-heading
    %h4.panel-title Latest Reviews of Nintendo
  .panel-body
    / List group
    .list-group
      %a.list-group-item(href="/")
        %h5.list-group-item-heading 1. Aaron
        %p.list-group-item-text <em>Cras justo odio.</em> – 24 Jan 2016
      %a.list-group-item(href="/")
        %h5.list-group-item-heading 2. John
        %p.list-group-item-text <em>Cras justo odio.</em> – 10 Jan 2016
      %a.list-group-item(href="/")
        %h5.list-group-item-heading 3. Morgan
        %p.list-group-item-text <em>Cras justo odio.</em> – 7 Jan 2016
      %a.list-group-item(href="/")
        %h5.list-group-item-heading 4. Carly
        %p.list-group-item-text <em>Cras justo odio.</em> – 1 jan 2016
    / New review form
    %form
      .form-group
        %label.col-sm-2.control-label(for="inputEmail3") Review Text
        .col-sm-10
        %textarea.form-control(placeholder="Type your review here." rows="4")
      .form-group
        .col-sm-10
          %button.btn.btn-primary(type="submit") Submit Review

app/views/ui/business_search_results.html.haml
.panel.panel-primary
  / Default panel contents
  .panel-heading
    %h4.panel-title Search Results
  .panel-body
    %p We found 5 businesses that match your search:
  / List group
  .list-group
  %a.list-group-item(href="")
    %h5.list-group-item-heading 1. Nintendo
    %p.list-group-item-text <em>Smash 4 is a great game on the Wii U!</em>
  %a.list-group-item(href="")
    %h5.list-group-item-heading 2. Microsoft
    %p.list-group-item-text <em>Microsoft is catching up quickly in terms of modern development support!</em>
  %a.list-group-item(href="")
    %h5.list-group-item-heading 3. Apple
    %p.list-group-item-text <em>Apple laptops continue to shine, generally.</em>
  %a.list-group-item(href="")
    %h5.list-group-item-heading 4. Facebook
    %p.list-group-item-text <em>React Native is a game-changer for mobile development!</em>
  %a.list-group-item(href="")
    %h5.list-group-item-heading 5. Docker
    %p.list-group-item-text <em>Docker makes Immutable Infrastructure more attainable</em>

app/views/ui/home.html.haml
.panel.panel-primary
  / Default panel contents
  .panel-heading
    %h4.panel-title Businesses
  .panel-body
    %p Check out some of the latest businesses registered to Yelpr!
  / List group
  .list-group
  %a.list-group-item(href="")
    %h5.list-group-item-heading 1. Nintendo
    %p.list-group-item-text <em>Smash 4 is a great game on the Wii U!</em>
  %a.list-group-item(href="")
    %h5.list-group-item-heading 2. Microsoft
    %p.list-group-item-text <em>Microsoft is catching up quickly in terms of modern development support!</em>
  %a.list-group-item(href="")
    %h5.list-group-item-heading 3. Apple
    %p.list-group-item-text <em>Apple laptops continue to shine, generally.</em>
  %a.list-group-item(href="")
    %h5.list-group-item-heading 4. Facebook
    %p.list-group-item-text <em>React Native is a game-changer for mobile development!</em>
  %a.list-group-item(href="")
    %h5.list-group-item-heading 5. Docker
    %p.list-group-item-text <em>Docker makes Immutable Infrastructure more attainable</em>

app/views/ui/index.html.haml
.list-group
%a.list-group-item(href="/ui/home")
  %h5.list-group-item-heading Home
%a.list-group-item(href="/ui/register")
  %h5.list-group-item-heading Register
%a.list-group-item(href="/ui/login")
  %h5.list-group-item-heading Login
%a.list-group-item(href="/ui/user_profile")
  %h5.list-group-item-heading User Profile
%a.list-group-item(href="/ui/add_business")
  %h5.list-group-item-heading Add Business
%a.list-group-item(href="/ui/business_search_results")
  %h5.list-group-item-heading Business Search Results
%a.list-group-item(href="/ui/business_profile")
  %h5.list-group-item-heading Business Profile
%a.list-group-item(href="/ui/recent_reviews")
  %h5.list-group-item-heading Recent Reviews

app/views/ui/login.html.haml
.panel.panel-primary
  .panel-heading
    %h4.panel-title Please sign in
  .panel-body
    %form.form-horizontal
      .form-group
        %label.col-sm-2.control-label(for="inputEmail3") Email
        .col-sm-10
          %input#inputEmail3.form-control(placeholder="Email" :type="email")
      .form-group
        %label.col-sm-2.control-label(for="inputPassword3") Password
        .col-sm-10
          %input#inputPassword3.form-control(placeholder="Password" type="password")
      .form-group
        .col-sm-offset-2.col-sm-10
          %button.btn.btn-primary(type="submit") Sign In

app/views/ui/recent_reviews.html.haml
.panel.panel-primary
  / Default panel contents
  .panel-heading
    %h4.panel-title Recent Reviews:
  .panel-body
    / List group
    .list-group
      %a.list-group-item(href="/")
        %h5.list-group-item-heading 1. Nintendo
        %p.list-group-item-text <em>Cras justo odio.</em> – 24 Jan 2016
      %a.list-group-item(href="/")
        %h5.list-group-item-heading 2. Apple
        %p.list-group-item-text <em>Cras justo odio.</em> – 10 Jan 2016
      %a.list-group-item(href="/")
        %h5.list-group-item-heading 3. Sony
        %p.list-group-item-text <em>Cras justo odio.</em> – 7 Jan 2016
      %a.list-group-item(href="/")
        %h5.list-group-item-heading 4. Samsung
        %p.list-group-item-text <em>Cras justo odio.</em> – 1 jan 2016

app/views/ui/register.html.haml
.panel.panel-primary
  .panel-heading
    %h4.panel-title Register with Yelpr!
  .panel-body
    %form.form-horizontal
      .form-group
        %label.col-sm-2.control-label(for="inputEmail3") Email
        .col-sm-10
          %input#inputEmail3.form-control(placeholder="Email" :type="email")
      .form-group
        %label.col-sm-2.control-label(for="inputPassword3") Password
        .col-sm-10
          %input#inputPassword3.form-control(placeholder="Password" type="password")
      .form-group
        .col-sm-offset-2.col-sm-10
          %button.btn.btn-primary(type="submit") Sign Up

app/views/ui/user_profile.html.haml
.panel.panel-primary
  / Default panel contents
  .panel-heading
    %h4.panel-title Aaron's Latest Reviews
  .panel-body
    / List group
    .list-group
      %a.list-group-item(href="/")
        %h5.list-group-item-heading 1. Nintendo
        %p.list-group-item-text <em>Cras justo odio.</em> – 24 Jan 2016
      %a.list-group-item(href="/")
        %h5.list-group-item-heading 2. Apple
        %p.list-group-item-text <em>Cras justo odio.</em> – 10 Jan 2016
      %a.list-group-item(href="/")
        %h5.list-group-item-heading 3. Sony
        %p.list-group-item-text <em>Cras justo odio.</em> – 7 Jan 2016
      %a.list-group-item(href="/")
        %h5.list-group-item-heading 4. Samsung
        %p.list-group-item-text <em>Cras justo odio.</em> – 1 jan 2016

app/views/users/new.html.haml
.panel.panel-primary
  .panel-heading
    %h4.panel-title Register with Yelpr!
  .panel-body
    =bootstrap_form_for @user, layout: :horizontal, label_col: 'col-sm-2', control_col: 'col-sm-6' do |f|
      %fieldset
        =f.text_field :username
        =f.email_field :email
        =f.password_field :password
      %fieldset.actions.control-group.col-sm-offset-2
        %button.btn.btn-primary(type="submit") Sign Up

app/views/users/show.html.haml
.panel.panel-primary
  / Default panel contents
  .panel-heading
    %h4.panel-title #{@user.username}'s latest reviews:
  .panel-body
    / List group
    .list-group
      = render @user.reviews